name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    # Optional: only run when site files change
    paths:
      - '**.html'
      - 'assets/**'
      - '!README.md'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Cancel older runs of this workflow for the same branch
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you ever build assets, run that here (npm build, etc.)

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Deploy the repo root (static site: index.html, /assets, etc.)
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
